backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  repo: fessehaye/galint-gaming
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Featured Events"
        name: "events"
        file: "src/_data/featuredevents.yaml"
        fields:
          - label: Game Event
            name: events
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Background Image, name: background, widget: image }
              - { label: Icon Image, name: icon, widget: image }
              - { label: URL, name: url, widget: string }
